export enum Recurso {
	OPORTUNIDADE_VIEW = 'OPORTUNIDADE_VIEW',
	OPORTUNIDADE_CREATE = 'OPORTUNIDADE_CREATE',
	OPORTUNIDADE_UPDATE = 'OPORTUNIDADE_UPDATE',
	OPORTUNIDADE_REMOVE = 'OPORTUNIDADE_REMOVE',
}
